In [37]:
# Import Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
pd.set_option('display.max_rows',50)

In [38]:
home_df.head()

  Assessor Neighborhood  Closed Roll Year  Assessed Land Value  Pct Change
0      Western Addition              2007          356275.8802        0.00
1      Western Addition              2008          384701.6860        7.98
2      Western Addition              2009          399153.2561        3.76
3      Western Addition              2010          411813.4324        3.17
4      Western Addition              2011          425384.5578        3.30

In [49]:
# Create a path to the csv and read it into a Pandas DataFrame
#csv_path = "Assessor_Historical_Secured_Property_Tax_Rolls.csv"
csv_path = "combine_updated2.csv"
rent_path = "rent_year_csv.csv"
home_df = pd.read_csv(csv_path, encoding='utf8', engine='python')
rent_df = pd.read_csv(rent_path, encoding='utf8', engine='python')

home_df.head(20)

,Unnamed: 0,Assessor Neighborhood,Closed Roll Year,Assessed Land Value,Pct Change
0,0,Bayview,2007,146817.391167,0
1,1,Bayview,2008,155151.982767,0
2,2,Bayview,2009,171617.607600,0
3,3,Bayview,2010,175450.544900,0
4,4,Bayview,2011,175691.806133,0
5,5,Bayview,2012,177818.914467,0
6,6,Bayview,2013,182203.741400,0
7,7,Bayview,2014,185691.451367,0
8,8,Bayview,2015,198571.039233,0
9,9,Bayview,2016,223100.197133,0
10,10,Bernal Heights,2007,186774.852000,0
11,11,Bernal Heights,2008,205277.049500,0
12,12,Bernal Heights,2009,217385.812000,0
13,13,Bernal Heights,2010,220154.296100,0
14,14,Bernal Heights,2011,228865.782800,0
15,15,Bernal Heights,2012,241607.198400,0
16,16,Bernal Heights,2013,252609.859300,0
17,17,Bernal Heights,2014,270243.422800,0
18,18,Bernal Heights,2015,292751.019900,0
19,19,Bernal Heights,2016,324871.445700,0

In [50]:
rent_df.columns

Index(['Region Name', 'Region Type', 'Data Type', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018'],
      dtype='object')

In [51]:
my_col_names = list(rent_df.columns.values)[3:]
melted_df = pd.melt(rent_df,id_vars=["Region Name","Region Type","Data Type"],value_vars=my_col_names,var_name="year",value_name="dollars")

In [52]:
rent_df = melted_df.rename(columns={'Region Name': 'Assessor Neighborhood'})

In [53]:
home_df.head()
rent_df["year"] = rent_df["year"].astype("int64")

In [54]:
home_df = home_df.drop("Unnamed: 0",axis = 1)

In [57]:
home_df

    Assessor Neighborhood  Closed Roll Year  Assessed Land Value  Pct Change
0                 Bayview              2007        146817.391167           0
1                 Bayview              2008        155151.982767           0
2                 Bayview              2009        171617.607600           0
3                 Bayview              2010        175450.544900           0
4                 Bayview              2011        175691.806133           0
5                 Bayview              2012        177818.914467           0
6                 Bayview              2013        182203.741400           0
7                 Bayview              2014        185691.451367           0
8                 Bayview              2015        198571.039233           0
9                 Bayview              2016        223100.197133           0
10         Bernal Heights              2007        186774.852000           0
11         Bernal Heights              2008        205277.049500           0
12         Bernal Heights              2009        217385.812000           0
13         Bernal Heights              2010        220154.296100           0
14         Bernal Heights              2011        228865.782800           0
15         Bernal Heights              2012        241607.198400           0
16         Bernal Heights              2013        252609.859300           0
17         Bernal Heights              2014        270243.422800           0
18         Bernal Heights              2015        292751.019900           0
19         Bernal Heights              2016        324871.445700           0
20            Buena Vista              2007        353209.288100           0
21            Buena Vista              2008        374901.209700           0
22            Buena Vista              2009        392689.320600           0
23            Buena Vista              2010        401270.095200           0
24            Buena Vista              2011        422857.419400           0
..                    ...               ...                  ...         ...
593      Western Addition              2012        390879.835100           0
594      Western Addition              2013        397116.486567           0
595      Western Addition              2014        416479.755267           0
596      Western Addition              2015        438925.682767           0
597      Western Addition              2016        469037.684200           0
598    Westwood Highlands              2007        237474.755700           0
599    Westwood Highlands              2008        254955.662500           0
600    Westwood Highlands              2009        287138.480600           0
601    Westwood Highlands              2010        295258.025900           0
602    Westwood Highlands              2011        310130.998200           0
603    Westwood Highlands              2012        320309.284700           0
604    Westwood Highlands              2013        329153.003700           0
605    Westwood Highlands              2014        344339.629200           0
606    Westwood Highlands              2015        369263.393000           0
607    Westwood Highlands              2016        386926.317300           0
608         Westwood Park              2007        199627.014100           0
609         Westwood Park              2008        215511.852900           0
610         Westwood Park              2009        227212.361500           0
611         Westwood Park              2010        225447.718300           0
612         Westwood Park              2011        232168.281700           0
613         Westwood Park              2012        248945.325500           0
614         Westwood Park              2013        254389.303600           0
615         Westwood Park              2014        272476.956500           0
616         Westwood Park              2015        287522.178300           0
617         Westwood Park              2016        315942.496100           0

[618 rows x 4 columns]

In [58]:
merged = pd.merge(home_df,rent_df, 
                  how='inner',
                  left_on=["Assessor Neighborhood","Closed Roll Year"],
                  right_on=["Assessor Neighborhood","year"])
merged

,Assessor Neighborhood,Closed Roll Year,Assessed Land Value,Pct Change,Region Type,Data Type,year,dollars
0,Bayview,2011,175691.806133,0,neighborhood,All Homes,2011,"$2,852"
1,Bayview,2012,177818.914467,0,neighborhood,All Homes,2012,"$2,961"
2,Bayview,2013,182203.741400,0,neighborhood,All Homes,2013,"$3,250"
3,Bayview,2014,185691.451367,0,neighborhood,All Homes,2014,"$3,644"
4,Bayview,2015,198571.039233,0,neighborhood,All Homes,2015,"$4,162"
5,Bayview,2016,223100.197133,0,neighborhood,All Homes,2016,"$4,411"
6,Bernal Heights,2011,228865.782800,0,neighborhood,All Homes,2011,"$2,448"
7,Bernal Heights,2012,241607.198400,0,neighborhood,All Homes,2012,"$2,393"
8,Bernal Heights,2013,252609.859300,0,neighborhood,All Homes,2013,"$2,510"
9,Bernal Heights,2014,270243.422800,0,neighborhood,All Homes,2014,"$2,895"
10,Bernal Heights,2015,292751.019900,0,neighborhood,All Homes,2015,"$3,488"
11,Bernal Heights,2016,324871.445700,0,neighborhood,All Homes,2016,"$3,798"
12,Buena Vista,2011,422857.419400,0,neighborhood,All Homes,2011,"$2,864"
13,Buena Vista,2012,443629.306500,0,neighborhood,All Homes,2012,"$2,951"
14,Buena Vista,2013,474521.277100,0,neighborhood,All Homes,2013,"$3,273"
15,Buena Vista,2014,497350.767700,0,neighborhood,All Homes,2014,"$3,553"
16,Buena Vista,2015,524772.200300,0,neighborhood,All Homes,2015,"$4,543"
17,Buena Vista,2016,564796.080200,0,neighborhood,All Homes,2016,"$4,549"
18,Corona Heights,2011,342979.050400,0,neighborhood,All Homes,2011,"$3,554"
19,Corona Heights,2012,364459.862400,0,neighborhood,All Homes,2012,"$3,799"
20,Corona Heights,2013,379856.647000,0,neighborhood,All Homes,2013,"$4,139"
21,Corona Heights,2014,403671.123700,0,neighborhood,All Homes,2014,"$4,428"
22,Corona Heights,2015,424334.137500,0,neighborhood,All Homes,2015,"$5,106"
23,Corona Heights,2016,449347.919500,0,neighborhood,All Homes,2016,"$5,463"
24,Cow Hollow,2011,518223.255900,0,neighborhood,All Homes,2011,"$3,431"
...,...,...,...,...,...,...,...,...
345,Upper Market,2016,535998.971350,0,neighborhood,All Homes,2016,"$4,773"
346,Visitacion Valley,2011,145537.009300,0,neighborhood,All Homes,2011,"$3,091"
347,Visitacion Valley,2012,148580.239100,0,neighborhood,All Homes,2012,"$3,373"
348,Visitacion Valley,2013,155854.134800,0,neighborhood,All Homes,2013,"$3,564"
349,Visitacion Valley,2014,165360.865800,0,neighborhood,All Homes,2014,"$3,935"
350,Visitacion Valley,2015,175324.845900,0,neighborhood,All Homes,2015,"$4,682"
351,Visitacion Valley,2016,187287.206800,0,neighborhood,All Homes,2016,"$4,605"
352,Western Addition,2011,377315.851933,0,neighborhood,All Homes,2011,"$2,389"
353,Western Addition,2012,390879.835100,0,neighborhood,All Homes,2012,"$2,419"
354,Western Addition,2013,397116.486567,0,neighborhood,All Homes,2013,"$2,572"
355,Western Addition,2014,416479.755267,0,neighborhood,All Homes,2014,"$2,854"
356,Western Addition,2015,438925.682767,0,neighborhood,All Homes,2015,"$3,426"
357,Western Addition,2016,469037.684200,0,neighborhood,All Homes,2016,"$3,698"
358,Westwood Highlands,2011,310130.998200,0,neighborhood,All Homes,2011,"$2,838"
359,Westwood Highlands,2012,320309.284700,0,neighborhood,All Homes,2012,"$3,138"
360,Westwood Highlands,2013,329153.003700,0,neighborhood,All Homes,2013,"$3,653"
361,Westwood Highlands,2014,344339.629200,0,neighborhood,All Homes,2014,"$3,978"
362,Westwood Highlands,2015,369263.393000,0,neighborhood,All Homes,2015,"$4,552"
363,Westwood Highlands,2016,386926.317300,0,neighborhood,All Homes,2016,"$4,588"
364,Westwood Park,2011,232168.281700,0,neighborhood,All Homes,2011,"$3,203"
365,Westwood Park,2012,248945.325500,0,neighborhood,All Homes,2012,"$3,161"
366,Westwood Park,2013,254389.303600,0,neighborhood,All Homes,2013,"$3,128"
367,Westwood Park,2014,272476.956500,0,neighborhood,All Homes,2014,"$3,780"
368,Westwood Park,2015,287522.178300,0,neighborhood,All Homes,2015,"$4,595"
369,Westwood Park,2016,315942.496100,0,neighborhood,All Homes,2016,"$4,840"

In [61]:
merged = merged.drop("year", axis = 1)

In [62]:
merged

,Assessor Neighborhood,Closed Roll Year,Assessed Land Value,Pct Change,Region Type,Data Type,dollars
0,Bayview,2011,175691.806133,0,neighborhood,All Homes,"$2,852"
1,Bayview,2012,177818.914467,0,neighborhood,All Homes,"$2,961"
2,Bayview,2013,182203.741400,0,neighborhood,All Homes,"$3,250"
3,Bayview,2014,185691.451367,0,neighborhood,All Homes,"$3,644"
4,Bayview,2015,198571.039233,0,neighborhood,All Homes,"$4,162"
5,Bayview,2016,223100.197133,0,neighborhood,All Homes,"$4,411"
6,Bernal Heights,2011,228865.782800,0,neighborhood,All Homes,"$2,448"
7,Bernal Heights,2012,241607.198400,0,neighborhood,All Homes,"$2,393"
8,Bernal Heights,2013,252609.859300,0,neighborhood,All Homes,"$2,510"
9,Bernal Heights,2014,270243.422800,0,neighborhood,All Homes,"$2,895"
10,Bernal Heights,2015,292751.019900,0,neighborhood,All Homes,"$3,488"
11,Bernal Heights,2016,324871.445700,0,neighborhood,All Homes,"$3,798"
12,Buena Vista,2011,422857.419400,0,neighborhood,All Homes,"$2,864"
13,Buena Vista,2012,443629.306500,0,neighborhood,All Homes,"$2,951"
14,Buena Vista,2013,474521.277100,0,neighborhood,All Homes,"$3,273"
15,Buena Vista,2014,497350.767700,0,neighborhood,All Homes,"$3,553"
16,Buena Vista,2015,524772.200300,0,neighborhood,All Homes,"$4,543"
17,Buena Vista,2016,564796.080200,0,neighborhood,All Homes,"$4,549"
18,Corona Heights,2011,342979.050400,0,neighborhood,All Homes,"$3,554"
19,Corona Heights,2012,364459.862400,0,neighborhood,All Homes,"$3,799"
20,Corona Heights,2013,379856.647000,0,neighborhood,All Homes,"$4,139"
21,Corona Heights,2014,403671.123700,0,neighborhood,All Homes,"$4,428"
22,Corona Heights,2015,424334.137500,0,neighborhood,All Homes,"$5,106"
23,Corona Heights,2016,449347.919500,0,neighborhood,All Homes,"$5,463"
24,Cow Hollow,2011,518223.255900,0,neighborhood,All Homes,"$3,431"
...,...,...,...,...,...,...,...
345,Upper Market,2016,535998.971350,0,neighborhood,All Homes,"$4,773"
346,Visitacion Valley,2011,145537.009300,0,neighborhood,All Homes,"$3,091"
347,Visitacion Valley,2012,148580.239100,0,neighborhood,All Homes,"$3,373"
348,Visitacion Valley,2013,155854.134800,0,neighborhood,All Homes,"$3,564"
349,Visitacion Valley,2014,165360.865800,0,neighborhood,All Homes,"$3,935"
350,Visitacion Valley,2015,175324.845900,0,neighborhood,All Homes,"$4,682"
351,Visitacion Valley,2016,187287.206800,0,neighborhood,All Homes,"$4,605"
352,Western Addition,2011,377315.851933,0,neighborhood,All Homes,"$2,389"
353,Western Addition,2012,390879.835100,0,neighborhood,All Homes,"$2,419"
354,Western Addition,2013,397116.486567,0,neighborhood,All Homes,"$2,572"
355,Western Addition,2014,416479.755267,0,neighborhood,All Homes,"$2,854"
356,Western Addition,2015,438925.682767,0,neighborhood,All Homes,"$3,426"
357,Western Addition,2016,469037.684200,0,neighborhood,All Homes,"$3,698"
358,Westwood Highlands,2011,310130.998200,0,neighborhood,All Homes,"$2,838"
359,Westwood Highlands,2012,320309.284700,0,neighborhood,All Homes,"$3,138"
360,Westwood Highlands,2013,329153.003700,0,neighborhood,All Homes,"$3,653"
361,Westwood Highlands,2014,344339.629200,0,neighborhood,All Homes,"$3,978"
362,Westwood Highlands,2015,369263.393000,0,neighborhood,All Homes,"$4,552"
363,Westwood Highlands,2016,386926.317300,0,neighborhood,All Homes,"$4,588"
364,Westwood Park,2011,232168.281700,0,neighborhood,All Homes,"$3,203"
365,Westwood Park,2012,248945.325500,0,neighborhood,All Homes,"$3,161"
366,Westwood Park,2013,254389.303600,0,neighborhood,All Homes,"$3,128"
367,Westwood Park,2014,272476.956500,0,neighborhood,All Homes,"$3,780"
368,Westwood Park,2015,287522.178300,0,neighborhood,All Homes,"$4,595"
369,Westwood Park,2016,315942.496100,0,neighborhood,All Homes,"$4,840"

In [63]:
#combined.to_csv('combine.csv', sep=',', encoding='utf-8')

merged.to_csv('merged.csv', sep=',', encoding='utf-8')